package com.clickcraft.demo.models;

public enum ELocations {
    BEOGRAD, BOR, VALJEVO, VRANJE, VRŠAC, ZAJEČAR, ZRENJANIN, JAGODINA, KIKINDA, KRAGUJEVAC,
    KRALJEVO, KRUŠEVAC, LESKOVAC, LOZNICA, NIŠ, NOVI_PAZAR, NOVI_SAD, PANČCEVO, PIROT, POŽAREVAC,
    PRIŠTINA, PROKUPLJE, SMEDEREVO, SOMBOR, SREMSKA_MITROVICA, SUBOTICA, UŽICE, ČAČAK, ŠABAC,
    ADA, ALEKSANDROVAC, ALEKSINAC, ALIBUNAR, APATIN, ARANĐELOVAC, ARILJE, BABUŠNICA, BAJINA_BAŠTA,
    BATOČINA, BAĆ, BAČKA_PALANKA, BAČKA_TOPOLA, BAČKI_PETROVAC, BELA_PALANKA, BELA_CRKVA,
    BEOČIN, BEČEJ, BLACE, BOGATIĆ, BOJNIK, BOLJEVAC, BOSILEGRAD, BRUS, BUJANOVAC, VARVARIN,
    VELIKA_PLANA, VELIKO_GRADIŠTE, VLADIMIRCI, VLADIČIN_HAN, VLASOTINCE, VRBAS, VRNJAČKA_BANJA, GADŽIN_HAN, GOLUBAC, GORNJI_MILANOVAC, DESPOTOVAC,
    DIMITROVGRAD, DOLJEVAC, ŽABALJ, ŽABARI, ŽAGUBICA, ŽITIŠTE, ŽITORADJA,
    ZUBIN_POTOK, IVANJICA, INDĐIJA, IRIG, KANJIŽA, KLADOVO, KNJAŽEVAC,
    KOVAČICA, KOVIN, KOSJERIĆ, KOSOVSKA_KAMENICA, KOSOVSKA_MITROVICA, KOCELJEVA,
    KRUPANJ, KULA, KURŠUMLIJA, KUČEVO, LAJKOVAC, LAPOVO, LEBANE, LEPOSAVIĆ, LIPLJAN, LUČANI, LJIG,
    LJUBOVIJA, MAJDANPEK, MALI_ZVORNIK, MALI_IĐOŠ, MALO_CRNIĆE, MEDVEĐA, MEROŠINA, MIONICA, NEGOTIN,
    NOVA_VAROŠ, NOVA_CRNJA, NOVI_BEČEJ, NOVI_KNEŽEVAC, OPOVO, OSEČINA,
    ODŽACI, PARAĆIN, PETROVAC_NA_MLAVI, PEĆINCI, PLANDIŠTE, POŽEGA, PRIBOJ, PRIJEPOLJE, RAŽANJ, RAČA, RAŠKA, REKOVAC, RUMA, SVILAJNAC, SVRLJIG, SENTA, SEČANJ,
    SJENICA, SMEDEREVSKA_PALANKA, SOKOBANJA, SRBOBRAN, SREMSKI_KARLOVCI, STARA_PAZOVA,
    SUVA_REKA, SURDULICA, TEMERIN, TITEL, TOPOLA, TRGOVIŠTE, TRSTENIK, TUTIN, ĆICEVAC, ĆUPRIJA,
    UB, UROŠEVAC, CRNA_TRAVA, ČAJETINA, ČOKA, ŠID
}
